### ISSUE TITLE
Setting a value to 0 doesnt work

### ISSUE THREAD

**Issue by ay13** [toddmotto/vault#3]
I am storing the value of an incrementer in localstorage and i want to set the default number to 0. Using ```vault.set('currNum', 0);``` nothing happens. All the rest of the numbers are store with no problems.

Edit: it is because of ```if (!key || !value) return;```. This will fail when value = 0.

Would changing it to ```if (!key || value === undefined) return;``` work just as well?

**Comment by toddmotto** [comment]
Doh, this was a falsy value oversight on my part. Check out [v1.3.0](https://github.com/toddmotto/vault/blob/master/dist/vault.js#L16-L36) I've just pushed, should address this issue getting/setting. Also reduced some of the internal API (same public) to save a bit of code :)

**Comment by ay13** [comment]
Thanks. New version works great.
